# docker-compose.yml

services:
  db:
    image: postgres:15 # Using PostgreSQL version 15
    container_name: postgres_db_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/ # Persist database data
    env_file:
      - ./.env.db # Load database credentials
    ports:
      # Expose PostgreSQL port to host if you need to connect with an external DB tool
      # Be cautious with this in non-local environments.
      - "5432:5432"
    networks:
      - django_network
    healthcheck:
      # Test to check if PostgreSQL is ready
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s # Check every 10 seconds
      timeout: 5s   # Wait 5 seconds for the check to complete
      retries: 5    # Retry 5 times

  web:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile name
    container_name: django_app_dev
    # Command to run the Django development server
    # Includes waiting for DB, making migrations, and running the server with reload
    # Replace 'your_project_name' with your actual Django project directory name.
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      # Mount the current directory on the host to /app in the container
      # This allows for real-time code changes without rebuilding the image.
      - .:/app
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    env_file:
      - ./.env.django # Load Django specific environment variables
    depends_on:
      db:
        condition: service_healthy # Wait for the 'db' service to be healthy before starting 'web'
    networks:
      - django_network

  pgadmin:
    image: dpage/pgadmin4 # Official pgAdmin4 image
    container_name: pgadmin_dev
    env_file:
      - ./.env.pgadmin # Load pgAdmin credentials
    ports:
      - "5050:80" # Access pgAdmin on http://localhost:5050 (pgAdmin listens on port 80 internally)
    depends_on:
      db:
        condition: service_healthy # Wait for the 'db' service to be healthy
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin # Persist pgAdmin user data and server configurations
    networks:
      - django_network

volumes:
  postgres_dev_data: # Defines the named volume for PostgreSQL data
  pgadmin_dev_data:  # Defines the named volume for pgAdmin data

networks:
  django_network: # Defines the bridge network for services to communicate
    driver: bridge
