# Generated by Django 5.2.1 on 2025-05-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the external application.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the application.', null=True)),
                ('base_url', models.URLField(blank=True, help_text='Base URL of the external application (for reference or callbacks).', max_length=255, null=True)),
                ('api_key', models.CharField(editable=False, help_text='Generated API key for this application. Treat this like a password.', max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this application currently active and allowed to use the API?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, help_text='User who registered this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Application',
                'verbose_name_plural': 'Registered Applications',
                'ordering': ['name'],
            },
        ),
    ]
