# Generated by Django 5.2.2 on 2025-06-06 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Official name of the funding organization.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text="A brief description of the funder's mission and history.", null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('funder_type', models.CharField(blank=True, help_text='e.g., Foundation, Corporate, Government', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funder Profile',
                'verbose_name_plural': 'Funder Profiles',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The official title of the grant.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the grant, its goals, and eligibility criteria.')),
                ('source_name', models.CharField(choices=[('GRANTS_GOV', 'Grants.gov'), ('MANUAL', 'Manual Entry'), ('XML_UPLOAD', 'XML Upload')], default='MANUAL', help_text='The original source of this grant data.', max_length=50)),
                ('source_id', models.CharField(blank=True, help_text='The unique identifier from the original source (e.g., opportunityId from Grants.gov).', max_length=100, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Specific eligibility requirements for applicants.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this grant currently open for applications?')),
                ('source_url', models.URLField(blank=True, help_text='Direct URL to the grant application or information page.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('funder', models.ForeignKey(help_text='The funding organization offering this grant.', on_delete=django.db.models.deletion.PROTECT, related_name='grant_opportunities', to='fund_finder.funderprofile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Opportunity',
                'verbose_name_plural': 'Grant Opportunities',
                'ordering': ['-application_deadline', 'title'],
                'abstract': False,
                'unique_together': {('source_name', 'source_id')},
            },
        ),
    ]
