# Generated by Django 5.2.2 on 2025-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funderprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this funder profile currently active and visible?'),
        ),
    ]
