# Generated by Django 5.2.2 on 2025-06-07 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fund_finder', '0002_funderprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantopportunity',
            old_name='eligibility_criteria',
            new_name='eligibility_criteria_text',
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='geographic_focus',
            field=models.CharField(blank=True, help_text='e.g., National, State of California, Local (Urban)', max_length=255),
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that entered this funder profile. Null for global funders.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder_profiles', to='core.organization'),
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='past_funding_notes',
            field=models.TextField(blank=True, help_text='Notes on past funding history or priorities.', null=True),
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='program_areas',
            field=models.TextField(blank=True, help_text='Comma-separated list of focus areas (e.g., STEM, Arts, Financial Literacy)'),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='funding_activity_category',
            field=models.CharField(blank=True, help_text='e.g., Education, Health, Community Development.', max_length=255),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='funding_instrument_type',
            field=models.CharField(blank=True, help_text='e.g., Grant, Cooperative Agreement, Loan.', max_length=100),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this grant (e.g., youth, STEM, at-risk).'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='source_id',
            field=models.CharField(blank=True, help_text='The unique identifier from the source (e.g., opportunityId from Grants.gov).', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FunderType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the funder type (e.g., Private Foundation).', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that created and can use this type. Null for system-level types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder_types', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funder Type',
                'verbose_name_plural': 'Funder Types',
                'ordering': ['organization__name', 'name'],
                'abstract': False,
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='funder_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funders', to='fund_finder.fundertype'),
        ),
    ]
