# Generated by Django 5.2.2 on 2025-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0003_rename_eligibility_criteria_grantopportunity_eligibility_criteria_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundertype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this funder type available for use?'),
        ),
    ]
