# Generated by Django 5.2.2 on 2025-06-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0004_fundertype_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantopportunity',
            options={'ordering': ['-close_date', '-posted_date', 'title'], 'verbose_name': 'Grant Opportunity', 'verbose_name_plural': 'Grant Opportunities'},
        ),
        migrations.RenameField(
            model_name='grantopportunity',
            old_name='application_deadline',
            new_name='close_date',
        ),
        migrations.RemoveField(
            model_name='funderprofile',
            name='past_funding_notes',
        ),
        migrations.RemoveField(
            model_name='grantopportunity',
            name='eligibility_criteria_text',
        ),
        migrations.RemoveField(
            model_name='grantopportunity',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='grantopportunity',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='grantopportunity',
            name='tags',
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='agency_code',
            field=models.CharField(blank=True, help_text="Agency code, e.g., 'DOL-ETA' from Grants.gov.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funderprofile',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Contact person, phone, or email for the funder.', null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='assistance_listings',
            field=models.CharField(blank=True, help_text='Assistance Listing Numbers (formerly CFDA).', max_length=255),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='award_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='award_floor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='cost_sharing_requirement',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='estimated_total_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='expected_number_of_awards',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('FORECASTED', 'Forecasted'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='POSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='version',
            field=models.CharField(blank=True, help_text="Version from the source, e.g., 'Synopsis 1'.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='description',
            field=models.TextField(help_text='Full funding description of the grant.'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_opportunities', to='fund_finder.funderprofile'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funding_activity_category',
            field=models.CharField(blank=True, help_text='e.g., Employment, Labor and Training.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funding_instrument_type',
            field=models.CharField(blank=True, help_text='e.g., Grant, Cooperative Agreement, Loan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this grant opportunity considered active in our system?'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='source_id',
            field=models.CharField(blank=True, help_text='The unique opportunity number/ID from the source.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='source_name',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
