# Generated by Django 5.2.2 on 2025-06-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0005_alter_grantopportunity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantopportunity',
            name='eligibility_criteria_text',
            field=models.TextField(blank=True, help_text='Specific eligibility requirements for applicants.', null=True),
        ),
        migrations.AddField(
            model_name='grantopportunity',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this grant (e.g., youth, STEM, at-risk).'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funding_activity_category',
            field=models.CharField(blank=True, help_text='e.g., Education, Health, Community Development.', max_length=255),
        ),
    ]
