# Generated by Django 5.2.2 on 2025-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0006_grantopportunity_eligibility_criteria_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantopportunity',
            name='assistance_listings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funding_activity_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='funding_instrument_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
