# Generated by Django 5.2.2 on 2025-06-08 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fund_finder', '0007_alter_grantopportunity_assistance_listings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funderprofile',
            name='agency_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='geographic_focus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder_profiles', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='funderprofile',
            name='program_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fundertype',
            name='name',
            field=models.CharField(help_text='Name of the funder type.', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundertype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder_types', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='eligibility_criteria_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for this grant.'),
        ),
        migrations.AlterField(
            model_name='grantopportunity',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for this import.', max_length=255, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('log_output', models.TextField(blank=True, help_text='Detailed log of successes and failures during the import.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Import Log',
                'verbose_name_plural': 'Data Import Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
