# Generated by Django 5.2.3 on 2025-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_finder', '0008_alter_funderprofile_agency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantopportunity',
            name='indexing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INDEXING', 'Indexing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Vector-store ingestion status: Pending → Indexing → Success/Failed', max_length=10),
        ),
    ]
